### ISSUE TITLE
composer.json type field wrong?

### ISSUE THREAD

**Issue by jenswegar** [unn/taxonomy_menu#4]
It seems the type of the module inside the composer.json is wrong, as the module is installed under vendor and not under modules/contrib when running `composer require drupal/taxonomy_menu` on a Drupal 8 installation. Having the module installed under modules/contrib seems necessary for Drupal to be able to pick up the new module when using a composer based installation and not using Drush? 

composer.json actual:
```
...
  "type": "module",
...

```
expected:
```
...
  "type": "drupal-module",
...
```

This was using the 8.x-3.x branch

**Comment by IngoVals** [comment]
This has already been fixed, just hasn't made a release yet.

You can use the dev branch instead of a release if you would like.

Via composer `composer require drupal/taxonomy_menu:3.x-dev` gives you the most up to date version and will result in the module being moved to the `web/module/contrib/`  folder.

[See commit here](https://github.com/unn/taxonomy_menu/commit/57fb941247d30299af3da139b1b49911362b346e)
